### PR TITLE
Overridable highlight groups

### PR DESCRIPTION
**Pull request by garybernhardt**
My green is very light; I need to override GreenBar to make it readable.

### CODE REVIEW

**Comment by reinh** [comment]
Can you do this in your colorscheme or your vimrc?

**Comment by garybernhardt** [comment]
Yeah, that's what I'm doing here. I didn't change the colors; I just moved their definition. They were in a function before, which smashed my customization every time MakeGreen ran. :)

**Comment by reinh** [comment]
Oh I see what you mean. Doh!

**Comment by reinh** [comment]
Merged in your commit, thanks!

**Pull request merged**
